// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/pbCreate.proto

#ifndef PROTOBUF_proto_2fpbCreate_2eproto__INCLUDED
#define PROTOBUF_proto_2fpbCreate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto/pbSpell.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fpbCreate_2eproto();
void protobuf_AssignDesc_proto_2fpbCreate_2eproto();
void protobuf_ShutdownFile_proto_2fpbCreate_2eproto();

class pbCreateClient;
class pbCreateDB;

// ===================================================================

class pbCreateClient : public ::google::protobuf::Message {
 public:
  pbCreateClient();
  virtual ~pbCreateClient();

  pbCreateClient(const pbCreateClient& from);

  inline pbCreateClient& operator=(const pbCreateClient& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const pbCreateClient& default_instance();

  void Swap(pbCreateClient* other);

  // implements Message ----------------------------------------------

  pbCreateClient* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const pbCreateClient& from);
  void MergeFrom(const pbCreateClient& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 hp = 1;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 1;
  inline ::google::protobuf::int32 hp() const;
  inline void set_hp(::google::protobuf::int32 value);

  // required int32 mp = 2;
  inline bool has_mp() const;
  inline void clear_mp();
  static const int kMpFieldNumber = 2;
  inline ::google::protobuf::int32 mp() const;
  inline void set_mp(::google::protobuf::int32 value);

  // repeated int32 props = 3;
  inline int props_size() const;
  inline void clear_props();
  static const int kPropsFieldNumber = 3;
  inline ::google::protobuf::int32 props(int index) const;
  inline void set_props(int index, ::google::protobuf::int32 value);
  inline void add_props(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      props() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_props();

  // repeated .pbSpellClient spells = 4;
  inline int spells_size() const;
  inline void clear_spells();
  static const int kSpellsFieldNumber = 4;
  inline const ::pbSpellClient& spells(int index) const;
  inline ::pbSpellClient* mutable_spells(int index);
  inline ::pbSpellClient* add_spells();
  inline const ::google::protobuf::RepeatedPtrField< ::pbSpellClient >&
      spells() const;
  inline ::google::protobuf::RepeatedPtrField< ::pbSpellClient >*
      mutable_spells();

  // @@protoc_insertion_point(class_scope:pbCreateClient)
 private:
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_mp();
  inline void clear_has_mp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 mp_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > props_;
  ::google::protobuf::RepeatedPtrField< ::pbSpellClient > spells_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fpbCreate_2eproto();
  friend void protobuf_AssignDesc_proto_2fpbCreate_2eproto();
  friend void protobuf_ShutdownFile_proto_2fpbCreate_2eproto();

  void InitAsDefaultInstance();
  static pbCreateClient* default_instance_;
};
// -------------------------------------------------------------------

class pbCreateDB : public ::google::protobuf::Message {
 public:
  pbCreateDB();
  virtual ~pbCreateDB();

  pbCreateDB(const pbCreateDB& from);

  inline pbCreateDB& operator=(const pbCreateDB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const pbCreateDB& default_instance();

  void Swap(pbCreateDB* other);

  // implements Message ----------------------------------------------

  pbCreateDB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const pbCreateDB& from);
  void MergeFrom(const pbCreateDB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 hp = 1;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 1;
  inline ::google::protobuf::int32 hp() const;
  inline void set_hp(::google::protobuf::int32 value);

  // repeated int32 props = 2;
  inline int props_size() const;
  inline void clear_props();
  static const int kPropsFieldNumber = 2;
  inline ::google::protobuf::int32 props(int index) const;
  inline void set_props(int index, ::google::protobuf::int32 value);
  inline void add_props(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      props() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_props();

  // required int32 level = 3;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 3;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pbCreateDB)
 private:
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_level();
  inline void clear_has_level();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > props_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 level_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fpbCreate_2eproto();
  friend void protobuf_AssignDesc_proto_2fpbCreate_2eproto();
  friend void protobuf_ShutdownFile_proto_2fpbCreate_2eproto();

  void InitAsDefaultInstance();
  static pbCreateDB* default_instance_;
};
// ===================================================================


// ===================================================================

// pbCreateClient

// required int32 hp = 1;
inline bool pbCreateClient::has_hp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void pbCreateClient::set_has_hp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void pbCreateClient::clear_has_hp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void pbCreateClient::clear_hp() {
  hp_ = 0;
  clear_has_hp();
}
inline ::google::protobuf::int32 pbCreateClient::hp() const {
  return hp_;
}
inline void pbCreateClient::set_hp(::google::protobuf::int32 value) {
  set_has_hp();
  hp_ = value;
}

// required int32 mp = 2;
inline bool pbCreateClient::has_mp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void pbCreateClient::set_has_mp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void pbCreateClient::clear_has_mp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void pbCreateClient::clear_mp() {
  mp_ = 0;
  clear_has_mp();
}
inline ::google::protobuf::int32 pbCreateClient::mp() const {
  return mp_;
}
inline void pbCreateClient::set_mp(::google::protobuf::int32 value) {
  set_has_mp();
  mp_ = value;
}

// repeated int32 props = 3;
inline int pbCreateClient::props_size() const {
  return props_.size();
}
inline void pbCreateClient::clear_props() {
  props_.Clear();
}
inline ::google::protobuf::int32 pbCreateClient::props(int index) const {
  return props_.Get(index);
}
inline void pbCreateClient::set_props(int index, ::google::protobuf::int32 value) {
  props_.Set(index, value);
}
inline void pbCreateClient::add_props(::google::protobuf::int32 value) {
  props_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
pbCreateClient::props() const {
  return props_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
pbCreateClient::mutable_props() {
  return &props_;
}

// repeated .pbSpellClient spells = 4;
inline int pbCreateClient::spells_size() const {
  return spells_.size();
}
inline void pbCreateClient::clear_spells() {
  spells_.Clear();
}
inline const ::pbSpellClient& pbCreateClient::spells(int index) const {
  return spells_.Get(index);
}
inline ::pbSpellClient* pbCreateClient::mutable_spells(int index) {
  return spells_.Mutable(index);
}
inline ::pbSpellClient* pbCreateClient::add_spells() {
  return spells_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pbSpellClient >&
pbCreateClient::spells() const {
  return spells_;
}
inline ::google::protobuf::RepeatedPtrField< ::pbSpellClient >*
pbCreateClient::mutable_spells() {
  return &spells_;
}

// -------------------------------------------------------------------

// pbCreateDB

// required int32 hp = 1;
inline bool pbCreateDB::has_hp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void pbCreateDB::set_has_hp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void pbCreateDB::clear_has_hp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void pbCreateDB::clear_hp() {
  hp_ = 0;
  clear_has_hp();
}
inline ::google::protobuf::int32 pbCreateDB::hp() const {
  return hp_;
}
inline void pbCreateDB::set_hp(::google::protobuf::int32 value) {
  set_has_hp();
  hp_ = value;
}

// repeated int32 props = 2;
inline int pbCreateDB::props_size() const {
  return props_.size();
}
inline void pbCreateDB::clear_props() {
  props_.Clear();
}
inline ::google::protobuf::int32 pbCreateDB::props(int index) const {
  return props_.Get(index);
}
inline void pbCreateDB::set_props(int index, ::google::protobuf::int32 value) {
  props_.Set(index, value);
}
inline void pbCreateDB::add_props(::google::protobuf::int32 value) {
  props_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
pbCreateDB::props() const {
  return props_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
pbCreateDB::mutable_props() {
  return &props_;
}

// required int32 level = 3;
inline bool pbCreateDB::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void pbCreateDB::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void pbCreateDB::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void pbCreateDB::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 pbCreateDB::level() const {
  return level_;
}
inline void pbCreateDB::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fpbCreate_2eproto__INCLUDED
