// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ChenyuanTypes.proto

#ifndef PROTOBUF_proto_2fChenyuanTypes_2eproto__INCLUDED
#define PROTOBUF_proto_2fChenyuanTypes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ChenyuanTypes {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fChenyuanTypes_2eproto();
void protobuf_AssignDesc_proto_2fChenyuanTypes_2eproto();
void protobuf_ShutdownFile_proto_2fChenyuanTypes_2eproto();

class PosSerializeDB;
class TalentPropSerializeDB;
class TalentNodeSerializeDB;
class PlayerSerializeDB;

// ===================================================================

class PosSerializeDB : public ::google::protobuf::Message {
 public:
  PosSerializeDB();
  virtual ~PosSerializeDB();

  PosSerializeDB(const PosSerializeDB& from);

  inline PosSerializeDB& operator=(const PosSerializeDB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PosSerializeDB& default_instance();

  void Swap(PosSerializeDB* other);

  // implements Message ----------------------------------------------

  PosSerializeDB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PosSerializeDB& from);
  void MergeFrom(const PosSerializeDB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 X = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 Y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ChenyuanTypes.PosSerializeDB)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fChenyuanTypes_2eproto();
  friend void protobuf_AssignDesc_proto_2fChenyuanTypes_2eproto();
  friend void protobuf_ShutdownFile_proto_2fChenyuanTypes_2eproto();

  void InitAsDefaultInstance();
  static PosSerializeDB* default_instance_;
};
// -------------------------------------------------------------------

class TalentPropSerializeDB : public ::google::protobuf::Message {
 public:
  TalentPropSerializeDB();
  virtual ~TalentPropSerializeDB();

  TalentPropSerializeDB(const TalentPropSerializeDB& from);

  inline TalentPropSerializeDB& operator=(const TalentPropSerializeDB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalentPropSerializeDB& default_instance();

  void Swap(TalentPropSerializeDB* other);

  // implements Message ----------------------------------------------

  TalentPropSerializeDB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TalentPropSerializeDB& from);
  void MergeFrom(const TalentPropSerializeDB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 PropId = 1;
  inline bool has_propid() const;
  inline void clear_propid();
  static const int kPropIdFieldNumber = 1;
  inline ::google::protobuf::int32 propid() const;
  inline void set_propid(::google::protobuf::int32 value);

  // required int32 PropVal = 2;
  inline bool has_propval() const;
  inline void clear_propval();
  static const int kPropValFieldNumber = 2;
  inline ::google::protobuf::int32 propval() const;
  inline void set_propval(::google::protobuf::int32 value);

  // required int32 Locked = 3;
  inline bool has_locked() const;
  inline void clear_locked();
  static const int kLockedFieldNumber = 3;
  inline ::google::protobuf::int32 locked() const;
  inline void set_locked(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ChenyuanTypes.TalentPropSerializeDB)
 private:
  inline void set_has_propid();
  inline void clear_has_propid();
  inline void set_has_propval();
  inline void clear_has_propval();
  inline void set_has_locked();
  inline void clear_has_locked();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 propid_;
  ::google::protobuf::int32 propval_;
  ::google::protobuf::int32 locked_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fChenyuanTypes_2eproto();
  friend void protobuf_AssignDesc_proto_2fChenyuanTypes_2eproto();
  friend void protobuf_ShutdownFile_proto_2fChenyuanTypes_2eproto();

  void InitAsDefaultInstance();
  static TalentPropSerializeDB* default_instance_;
};
// -------------------------------------------------------------------

class TalentNodeSerializeDB : public ::google::protobuf::Message {
 public:
  TalentNodeSerializeDB();
  virtual ~TalentNodeSerializeDB();

  TalentNodeSerializeDB(const TalentNodeSerializeDB& from);

  inline TalentNodeSerializeDB& operator=(const TalentNodeSerializeDB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalentNodeSerializeDB& default_instance();

  void Swap(TalentNodeSerializeDB* other);

  // implements Message ----------------------------------------------

  TalentNodeSerializeDB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TalentNodeSerializeDB& from);
  void MergeFrom(const TalentNodeSerializeDB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ChenyuanTypes.TalentPropSerializeDB Props = 1;
  inline int props_size() const;
  inline void clear_props();
  static const int kPropsFieldNumber = 1;
  inline const ::ChenyuanTypes::TalentPropSerializeDB& props(int index) const;
  inline ::ChenyuanTypes::TalentPropSerializeDB* mutable_props(int index);
  inline ::ChenyuanTypes::TalentPropSerializeDB* add_props();
  inline const ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentPropSerializeDB >&
      props() const;
  inline ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentPropSerializeDB >*
      mutable_props();

  // @@protoc_insertion_point(class_scope:ChenyuanTypes.TalentNodeSerializeDB)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentPropSerializeDB > props_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fChenyuanTypes_2eproto();
  friend void protobuf_AssignDesc_proto_2fChenyuanTypes_2eproto();
  friend void protobuf_ShutdownFile_proto_2fChenyuanTypes_2eproto();

  void InitAsDefaultInstance();
  static TalentNodeSerializeDB* default_instance_;
};
// -------------------------------------------------------------------

class PlayerSerializeDB : public ::google::protobuf::Message {
 public:
  PlayerSerializeDB();
  virtual ~PlayerSerializeDB();

  PlayerSerializeDB(const PlayerSerializeDB& from);

  inline PlayerSerializeDB& operator=(const PlayerSerializeDB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerSerializeDB& default_instance();

  void Swap(PlayerSerializeDB* other);

  // implements Message ----------------------------------------------

  PlayerSerializeDB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerSerializeDB& from);
  void MergeFrom(const PlayerSerializeDB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required int32 RoleId = 2;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 2;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // optional .ChenyuanTypes.PosSerializeDB Pos = 3;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 3;
  inline const ::ChenyuanTypes::PosSerializeDB& pos() const;
  inline ::ChenyuanTypes::PosSerializeDB* mutable_pos();
  inline ::ChenyuanTypes::PosSerializeDB* release_pos();
  inline void set_allocated_pos(::ChenyuanTypes::PosSerializeDB* pos);

  // repeated int32 SpellList = 4;
  inline int spelllist_size() const;
  inline void clear_spelllist();
  static const int kSpellListFieldNumber = 4;
  inline ::google::protobuf::int32 spelllist(int index) const;
  inline void set_spelllist(int index, ::google::protobuf::int32 value);
  inline void add_spelllist(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      spelllist() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_spelllist();

  // repeated .ChenyuanTypes.TalentNodeSerializeDB TalentNodes = 5;
  inline int talentnodes_size() const;
  inline void clear_talentnodes();
  static const int kTalentNodesFieldNumber = 5;
  inline const ::ChenyuanTypes::TalentNodeSerializeDB& talentnodes(int index) const;
  inline ::ChenyuanTypes::TalentNodeSerializeDB* mutable_talentnodes(int index);
  inline ::ChenyuanTypes::TalentNodeSerializeDB* add_talentnodes();
  inline const ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentNodeSerializeDB >&
      talentnodes() const;
  inline ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentNodeSerializeDB >*
      mutable_talentnodes();

  // @@protoc_insertion_point(class_scope:ChenyuanTypes.PlayerSerializeDB)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_pos();
  inline void clear_has_pos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::ChenyuanTypes::PosSerializeDB* pos_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > spelllist_;
  ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentNodeSerializeDB > talentnodes_;
  ::google::protobuf::int32 roleid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fChenyuanTypes_2eproto();
  friend void protobuf_AssignDesc_proto_2fChenyuanTypes_2eproto();
  friend void protobuf_ShutdownFile_proto_2fChenyuanTypes_2eproto();

  void InitAsDefaultInstance();
  static PlayerSerializeDB* default_instance_;
};
// ===================================================================


// ===================================================================

// PosSerializeDB

// required int32 X = 1;
inline bool PosSerializeDB::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PosSerializeDB::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PosSerializeDB::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PosSerializeDB::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 PosSerializeDB::x() const {
  return x_;
}
inline void PosSerializeDB::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 Y = 2;
inline bool PosSerializeDB::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PosSerializeDB::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PosSerializeDB::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PosSerializeDB::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 PosSerializeDB::y() const {
  return y_;
}
inline void PosSerializeDB::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// TalentPropSerializeDB

// required int32 PropId = 1;
inline bool TalentPropSerializeDB::has_propid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TalentPropSerializeDB::set_has_propid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TalentPropSerializeDB::clear_has_propid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TalentPropSerializeDB::clear_propid() {
  propid_ = 0;
  clear_has_propid();
}
inline ::google::protobuf::int32 TalentPropSerializeDB::propid() const {
  return propid_;
}
inline void TalentPropSerializeDB::set_propid(::google::protobuf::int32 value) {
  set_has_propid();
  propid_ = value;
}

// required int32 PropVal = 2;
inline bool TalentPropSerializeDB::has_propval() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TalentPropSerializeDB::set_has_propval() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TalentPropSerializeDB::clear_has_propval() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TalentPropSerializeDB::clear_propval() {
  propval_ = 0;
  clear_has_propval();
}
inline ::google::protobuf::int32 TalentPropSerializeDB::propval() const {
  return propval_;
}
inline void TalentPropSerializeDB::set_propval(::google::protobuf::int32 value) {
  set_has_propval();
  propval_ = value;
}

// required int32 Locked = 3;
inline bool TalentPropSerializeDB::has_locked() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TalentPropSerializeDB::set_has_locked() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TalentPropSerializeDB::clear_has_locked() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TalentPropSerializeDB::clear_locked() {
  locked_ = 0;
  clear_has_locked();
}
inline ::google::protobuf::int32 TalentPropSerializeDB::locked() const {
  return locked_;
}
inline void TalentPropSerializeDB::set_locked(::google::protobuf::int32 value) {
  set_has_locked();
  locked_ = value;
}

// -------------------------------------------------------------------

// TalentNodeSerializeDB

// repeated .ChenyuanTypes.TalentPropSerializeDB Props = 1;
inline int TalentNodeSerializeDB::props_size() const {
  return props_.size();
}
inline void TalentNodeSerializeDB::clear_props() {
  props_.Clear();
}
inline const ::ChenyuanTypes::TalentPropSerializeDB& TalentNodeSerializeDB::props(int index) const {
  return props_.Get(index);
}
inline ::ChenyuanTypes::TalentPropSerializeDB* TalentNodeSerializeDB::mutable_props(int index) {
  return props_.Mutable(index);
}
inline ::ChenyuanTypes::TalentPropSerializeDB* TalentNodeSerializeDB::add_props() {
  return props_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentPropSerializeDB >&
TalentNodeSerializeDB::props() const {
  return props_;
}
inline ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentPropSerializeDB >*
TalentNodeSerializeDB::mutable_props() {
  return &props_;
}

// -------------------------------------------------------------------

// PlayerSerializeDB

// required string Name = 1;
inline bool PlayerSerializeDB::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerSerializeDB::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerSerializeDB::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerSerializeDB::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& PlayerSerializeDB::name() const {
  return *name_;
}
inline void PlayerSerializeDB::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PlayerSerializeDB::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PlayerSerializeDB::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PlayerSerializeDB::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* PlayerSerializeDB::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PlayerSerializeDB::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 RoleId = 2;
inline bool PlayerSerializeDB::has_roleid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayerSerializeDB::set_has_roleid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayerSerializeDB::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayerSerializeDB::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 PlayerSerializeDB::roleid() const {
  return roleid_;
}
inline void PlayerSerializeDB::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
}

// optional .ChenyuanTypes.PosSerializeDB Pos = 3;
inline bool PlayerSerializeDB::has_pos() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PlayerSerializeDB::set_has_pos() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PlayerSerializeDB::clear_has_pos() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PlayerSerializeDB::clear_pos() {
  if (pos_ != NULL) pos_->::ChenyuanTypes::PosSerializeDB::Clear();
  clear_has_pos();
}
inline const ::ChenyuanTypes::PosSerializeDB& PlayerSerializeDB::pos() const {
  return pos_ != NULL ? *pos_ : *default_instance_->pos_;
}
inline ::ChenyuanTypes::PosSerializeDB* PlayerSerializeDB::mutable_pos() {
  set_has_pos();
  if (pos_ == NULL) pos_ = new ::ChenyuanTypes::PosSerializeDB;
  return pos_;
}
inline ::ChenyuanTypes::PosSerializeDB* PlayerSerializeDB::release_pos() {
  clear_has_pos();
  ::ChenyuanTypes::PosSerializeDB* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void PlayerSerializeDB::set_allocated_pos(::ChenyuanTypes::PosSerializeDB* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    set_has_pos();
  } else {
    clear_has_pos();
  }
}

// repeated int32 SpellList = 4;
inline int PlayerSerializeDB::spelllist_size() const {
  return spelllist_.size();
}
inline void PlayerSerializeDB::clear_spelllist() {
  spelllist_.Clear();
}
inline ::google::protobuf::int32 PlayerSerializeDB::spelllist(int index) const {
  return spelllist_.Get(index);
}
inline void PlayerSerializeDB::set_spelllist(int index, ::google::protobuf::int32 value) {
  spelllist_.Set(index, value);
}
inline void PlayerSerializeDB::add_spelllist(::google::protobuf::int32 value) {
  spelllist_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PlayerSerializeDB::spelllist() const {
  return spelllist_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PlayerSerializeDB::mutable_spelllist() {
  return &spelllist_;
}

// repeated .ChenyuanTypes.TalentNodeSerializeDB TalentNodes = 5;
inline int PlayerSerializeDB::talentnodes_size() const {
  return talentnodes_.size();
}
inline void PlayerSerializeDB::clear_talentnodes() {
  talentnodes_.Clear();
}
inline const ::ChenyuanTypes::TalentNodeSerializeDB& PlayerSerializeDB::talentnodes(int index) const {
  return talentnodes_.Get(index);
}
inline ::ChenyuanTypes::TalentNodeSerializeDB* PlayerSerializeDB::mutable_talentnodes(int index) {
  return talentnodes_.Mutable(index);
}
inline ::ChenyuanTypes::TalentNodeSerializeDB* PlayerSerializeDB::add_talentnodes() {
  return talentnodes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentNodeSerializeDB >&
PlayerSerializeDB::talentnodes() const {
  return talentnodes_;
}
inline ::google::protobuf::RepeatedPtrField< ::ChenyuanTypes::TalentNodeSerializeDB >*
PlayerSerializeDB::mutable_talentnodes() {
  return &talentnodes_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ChenyuanTypes

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fChenyuanTypes_2eproto__INCLUDED
