// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Rpc.proto

#ifndef PROTOBUF_proto_2fRpc_2eproto__INCLUDED
#define PROTOBUF_proto_2fRpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace RPCS {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fRpc_2eproto();
void protobuf_AssignDesc_proto_2fRpc_2eproto();
void protobuf_ShutdownFile_proto_2fRpc_2eproto();

class SRPCEquipEquipmentArg;
class SRPCEquipEquipmentRlt;
class SRPCUnEquipEquipmentArg;
class SRPCUnEquipEquipmentRlt;
class SRPCSellItemArg;
class SRPCSellItemRlt;
class SRPCUseItemArg;
class SRPCUseItemRlt;
class SRPCComposeItemArg;
class SRPCComposeItemRlt;
class SRPCSortItemsArg;
class SRPCSortItemsRlt;
class CRPCUpdateOneBagItem;
class CRPCUpdateOneEquipedItem;
class CRPCUpdateBagItems;

// ===================================================================

class SRPCEquipEquipmentArg : public ::google::protobuf::Message {
 public:
  SRPCEquipEquipmentArg();
  virtual ~SRPCEquipEquipmentArg();

  SRPCEquipEquipmentArg(const SRPCEquipEquipmentArg& from);

  inline SRPCEquipEquipmentArg& operator=(const SRPCEquipEquipmentArg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCEquipEquipmentArg& default_instance();

  void Swap(SRPCEquipEquipmentArg* other);

  // implements Message ----------------------------------------------

  SRPCEquipEquipmentArg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCEquipEquipmentArg& from);
  void MergeFrom(const SRPCEquipEquipmentArg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 itempos = 1;
  inline bool has_itempos() const;
  inline void clear_itempos();
  static const int kItemposFieldNumber = 1;
  inline ::google::protobuf::int32 itempos() const;
  inline void set_itempos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCEquipEquipmentArg)
 private:
  inline void set_has_itempos();
  inline void clear_has_itempos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 itempos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCEquipEquipmentArg* default_instance_;
};
// -------------------------------------------------------------------

class SRPCEquipEquipmentRlt : public ::google::protobuf::Message {
 public:
  SRPCEquipEquipmentRlt();
  virtual ~SRPCEquipEquipmentRlt();

  SRPCEquipEquipmentRlt(const SRPCEquipEquipmentRlt& from);

  inline SRPCEquipEquipmentRlt& operator=(const SRPCEquipEquipmentRlt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCEquipEquipmentRlt& default_instance();

  void Swap(SRPCEquipEquipmentRlt* other);

  // implements Message ----------------------------------------------

  SRPCEquipEquipmentRlt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCEquipEquipmentRlt& from);
  void MergeFrom(const SRPCEquipEquipmentRlt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 rs = 1;
  inline bool has_rs() const;
  inline void clear_rs();
  static const int kRsFieldNumber = 1;
  inline ::google::protobuf::int32 rs() const;
  inline void set_rs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCEquipEquipmentRlt)
 private:
  inline void set_has_rs();
  inline void clear_has_rs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 rs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCEquipEquipmentRlt* default_instance_;
};
// -------------------------------------------------------------------

class SRPCUnEquipEquipmentArg : public ::google::protobuf::Message {
 public:
  SRPCUnEquipEquipmentArg();
  virtual ~SRPCUnEquipEquipmentArg();

  SRPCUnEquipEquipmentArg(const SRPCUnEquipEquipmentArg& from);

  inline SRPCUnEquipEquipmentArg& operator=(const SRPCUnEquipEquipmentArg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCUnEquipEquipmentArg& default_instance();

  void Swap(SRPCUnEquipEquipmentArg* other);

  // implements Message ----------------------------------------------

  SRPCUnEquipEquipmentArg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCUnEquipEquipmentArg& from);
  void MergeFrom(const SRPCUnEquipEquipmentArg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 pos = 1;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 1;
  inline ::google::protobuf::int32 pos() const;
  inline void set_pos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCUnEquipEquipmentArg)
 private:
  inline void set_has_pos();
  inline void clear_has_pos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 pos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCUnEquipEquipmentArg* default_instance_;
};
// -------------------------------------------------------------------

class SRPCUnEquipEquipmentRlt : public ::google::protobuf::Message {
 public:
  SRPCUnEquipEquipmentRlt();
  virtual ~SRPCUnEquipEquipmentRlt();

  SRPCUnEquipEquipmentRlt(const SRPCUnEquipEquipmentRlt& from);

  inline SRPCUnEquipEquipmentRlt& operator=(const SRPCUnEquipEquipmentRlt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCUnEquipEquipmentRlt& default_instance();

  void Swap(SRPCUnEquipEquipmentRlt* other);

  // implements Message ----------------------------------------------

  SRPCUnEquipEquipmentRlt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCUnEquipEquipmentRlt& from);
  void MergeFrom(const SRPCUnEquipEquipmentRlt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 rs = 1;
  inline bool has_rs() const;
  inline void clear_rs();
  static const int kRsFieldNumber = 1;
  inline ::google::protobuf::int32 rs() const;
  inline void set_rs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCUnEquipEquipmentRlt)
 private:
  inline void set_has_rs();
  inline void clear_has_rs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 rs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCUnEquipEquipmentRlt* default_instance_;
};
// -------------------------------------------------------------------

class SRPCSellItemArg : public ::google::protobuf::Message {
 public:
  SRPCSellItemArg();
  virtual ~SRPCSellItemArg();

  SRPCSellItemArg(const SRPCSellItemArg& from);

  inline SRPCSellItemArg& operator=(const SRPCSellItemArg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCSellItemArg& default_instance();

  void Swap(SRPCSellItemArg* other);

  // implements Message ----------------------------------------------

  SRPCSellItemArg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCSellItemArg& from);
  void MergeFrom(const SRPCSellItemArg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 itempos = 1;
  inline bool has_itempos() const;
  inline void clear_itempos();
  static const int kItemposFieldNumber = 1;
  inline ::google::protobuf::int32 itempos() const;
  inline void set_itempos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCSellItemArg)
 private:
  inline void set_has_itempos();
  inline void clear_has_itempos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 itempos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCSellItemArg* default_instance_;
};
// -------------------------------------------------------------------

class SRPCSellItemRlt : public ::google::protobuf::Message {
 public:
  SRPCSellItemRlt();
  virtual ~SRPCSellItemRlt();

  SRPCSellItemRlt(const SRPCSellItemRlt& from);

  inline SRPCSellItemRlt& operator=(const SRPCSellItemRlt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCSellItemRlt& default_instance();

  void Swap(SRPCSellItemRlt* other);

  // implements Message ----------------------------------------------

  SRPCSellItemRlt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCSellItemRlt& from);
  void MergeFrom(const SRPCSellItemRlt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 money = 1;
  inline bool has_money() const;
  inline void clear_money();
  static const int kMoneyFieldNumber = 1;
  inline ::google::protobuf::int32 money() const;
  inline void set_money(::google::protobuf::int32 value);

  // required int32 badge = 2;
  inline bool has_badge() const;
  inline void clear_badge();
  static const int kBadgeFieldNumber = 2;
  inline ::google::protobuf::int32 badge() const;
  inline void set_badge(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCSellItemRlt)
 private:
  inline void set_has_money();
  inline void clear_has_money();
  inline void set_has_badge();
  inline void clear_has_badge();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 money_;
  ::google::protobuf::int32 badge_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCSellItemRlt* default_instance_;
};
// -------------------------------------------------------------------

class SRPCUseItemArg : public ::google::protobuf::Message {
 public:
  SRPCUseItemArg();
  virtual ~SRPCUseItemArg();

  SRPCUseItemArg(const SRPCUseItemArg& from);

  inline SRPCUseItemArg& operator=(const SRPCUseItemArg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCUseItemArg& default_instance();

  void Swap(SRPCUseItemArg* other);

  // implements Message ----------------------------------------------

  SRPCUseItemArg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCUseItemArg& from);
  void MergeFrom(const SRPCUseItemArg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 pos = 1;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 1;
  inline ::google::protobuf::int32 pos() const;
  inline void set_pos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCUseItemArg)
 private:
  inline void set_has_pos();
  inline void clear_has_pos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 pos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCUseItemArg* default_instance_;
};
// -------------------------------------------------------------------

class SRPCUseItemRlt : public ::google::protobuf::Message {
 public:
  SRPCUseItemRlt();
  virtual ~SRPCUseItemRlt();

  SRPCUseItemRlt(const SRPCUseItemRlt& from);

  inline SRPCUseItemRlt& operator=(const SRPCUseItemRlt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCUseItemRlt& default_instance();

  void Swap(SRPCUseItemRlt* other);

  // implements Message ----------------------------------------------

  SRPCUseItemRlt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCUseItemRlt& from);
  void MergeFrom(const SRPCUseItemRlt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 rs = 1;
  inline bool has_rs() const;
  inline void clear_rs();
  static const int kRsFieldNumber = 1;
  inline ::google::protobuf::int32 rs() const;
  inline void set_rs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCUseItemRlt)
 private:
  inline void set_has_rs();
  inline void clear_has_rs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 rs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCUseItemRlt* default_instance_;
};
// -------------------------------------------------------------------

class SRPCComposeItemArg : public ::google::protobuf::Message {
 public:
  SRPCComposeItemArg();
  virtual ~SRPCComposeItemArg();

  SRPCComposeItemArg(const SRPCComposeItemArg& from);

  inline SRPCComposeItemArg& operator=(const SRPCComposeItemArg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCComposeItemArg& default_instance();

  void Swap(SRPCComposeItemArg* other);

  // implements Message ----------------------------------------------

  SRPCComposeItemArg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCComposeItemArg& from);
  void MergeFrom(const SRPCComposeItemArg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // repeated int32 indexs = 2;
  inline int indexs_size() const;
  inline void clear_indexs();
  static const int kIndexsFieldNumber = 2;
  inline ::google::protobuf::int32 indexs(int index) const;
  inline void set_indexs(int index, ::google::protobuf::int32 value);
  inline void add_indexs(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      indexs() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_indexs();

  // @@protoc_insertion_point(class_scope:RPCS.SRPCComposeItemArg)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > indexs_;
  ::google::protobuf::int32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCComposeItemArg* default_instance_;
};
// -------------------------------------------------------------------

class SRPCComposeItemRlt : public ::google::protobuf::Message {
 public:
  SRPCComposeItemRlt();
  virtual ~SRPCComposeItemRlt();

  SRPCComposeItemRlt(const SRPCComposeItemRlt& from);

  inline SRPCComposeItemRlt& operator=(const SRPCComposeItemRlt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCComposeItemRlt& default_instance();

  void Swap(SRPCComposeItemRlt* other);

  // implements Message ----------------------------------------------

  SRPCComposeItemRlt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCComposeItemRlt& from);
  void MergeFrom(const SRPCComposeItemRlt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 rs = 1;
  inline bool has_rs() const;
  inline void clear_rs();
  static const int kRsFieldNumber = 1;
  inline ::google::protobuf::int32 rs() const;
  inline void set_rs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.SRPCComposeItemRlt)
 private:
  inline void set_has_rs();
  inline void clear_has_rs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 rs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCComposeItemRlt* default_instance_;
};
// -------------------------------------------------------------------

class SRPCSortItemsArg : public ::google::protobuf::Message {
 public:
  SRPCSortItemsArg();
  virtual ~SRPCSortItemsArg();

  SRPCSortItemsArg(const SRPCSortItemsArg& from);

  inline SRPCSortItemsArg& operator=(const SRPCSortItemsArg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCSortItemsArg& default_instance();

  void Swap(SRPCSortItemsArg* other);

  // implements Message ----------------------------------------------

  SRPCSortItemsArg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCSortItemsArg& from);
  void MergeFrom(const SRPCSortItemsArg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:RPCS.SRPCSortItemsArg)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCSortItemsArg* default_instance_;
};
// -------------------------------------------------------------------

class SRPCSortItemsRlt : public ::google::protobuf::Message {
 public:
  SRPCSortItemsRlt();
  virtual ~SRPCSortItemsRlt();

  SRPCSortItemsRlt(const SRPCSortItemsRlt& from);

  inline SRPCSortItemsRlt& operator=(const SRPCSortItemsRlt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRPCSortItemsRlt& default_instance();

  void Swap(SRPCSortItemsRlt* other);

  // implements Message ----------------------------------------------

  SRPCSortItemsRlt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRPCSortItemsRlt& from);
  void MergeFrom(const SRPCSortItemsRlt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:RPCS.SRPCSortItemsRlt)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static SRPCSortItemsRlt* default_instance_;
};
// -------------------------------------------------------------------

class CRPCUpdateOneBagItem : public ::google::protobuf::Message {
 public:
  CRPCUpdateOneBagItem();
  virtual ~CRPCUpdateOneBagItem();

  CRPCUpdateOneBagItem(const CRPCUpdateOneBagItem& from);

  inline CRPCUpdateOneBagItem& operator=(const CRPCUpdateOneBagItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CRPCUpdateOneBagItem& default_instance();

  void Swap(CRPCUpdateOneBagItem* other);

  // implements Message ----------------------------------------------

  CRPCUpdateOneBagItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CRPCUpdateOneBagItem& from);
  void MergeFrom(const CRPCUpdateOneBagItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 pos = 1;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 1;
  inline ::google::protobuf::int32 pos() const;
  inline void set_pos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.CRPCUpdateOneBagItem)
 private:
  inline void set_has_pos();
  inline void clear_has_pos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 pos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static CRPCUpdateOneBagItem* default_instance_;
};
// -------------------------------------------------------------------

class CRPCUpdateOneEquipedItem : public ::google::protobuf::Message {
 public:
  CRPCUpdateOneEquipedItem();
  virtual ~CRPCUpdateOneEquipedItem();

  CRPCUpdateOneEquipedItem(const CRPCUpdateOneEquipedItem& from);

  inline CRPCUpdateOneEquipedItem& operator=(const CRPCUpdateOneEquipedItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CRPCUpdateOneEquipedItem& default_instance();

  void Swap(CRPCUpdateOneEquipedItem* other);

  // implements Message ----------------------------------------------

  CRPCUpdateOneEquipedItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CRPCUpdateOneEquipedItem& from);
  void MergeFrom(const CRPCUpdateOneEquipedItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 pos = 1;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 1;
  inline ::google::protobuf::int32 pos() const;
  inline void set_pos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.CRPCUpdateOneEquipedItem)
 private:
  inline void set_has_pos();
  inline void clear_has_pos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 pos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static CRPCUpdateOneEquipedItem* default_instance_;
};
// -------------------------------------------------------------------

class CRPCUpdateBagItems : public ::google::protobuf::Message {
 public:
  CRPCUpdateBagItems();
  virtual ~CRPCUpdateBagItems();

  CRPCUpdateBagItems(const CRPCUpdateBagItems& from);

  inline CRPCUpdateBagItems& operator=(const CRPCUpdateBagItems& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CRPCUpdateBagItems& default_instance();

  void Swap(CRPCUpdateBagItems* other);

  // implements Message ----------------------------------------------

  CRPCUpdateBagItems* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CRPCUpdateBagItems& from);
  void MergeFrom(const CRPCUpdateBagItems& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 pos = 1;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 1;
  inline ::google::protobuf::int32 pos() const;
  inline void set_pos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RPCS.CRPCUpdateBagItems)
 private:
  inline void set_has_pos();
  inline void clear_has_pos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 pos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fRpc_2eproto();
  friend void protobuf_AssignDesc_proto_2fRpc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRpc_2eproto();

  void InitAsDefaultInstance();
  static CRPCUpdateBagItems* default_instance_;
};
// ===================================================================


// ===================================================================

// SRPCEquipEquipmentArg

// required int32 itempos = 1;
inline bool SRPCEquipEquipmentArg::has_itempos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCEquipEquipmentArg::set_has_itempos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCEquipEquipmentArg::clear_has_itempos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCEquipEquipmentArg::clear_itempos() {
  itempos_ = 0;
  clear_has_itempos();
}
inline ::google::protobuf::int32 SRPCEquipEquipmentArg::itempos() const {
  return itempos_;
}
inline void SRPCEquipEquipmentArg::set_itempos(::google::protobuf::int32 value) {
  set_has_itempos();
  itempos_ = value;
}

// -------------------------------------------------------------------

// SRPCEquipEquipmentRlt

// required int32 rs = 1;
inline bool SRPCEquipEquipmentRlt::has_rs() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCEquipEquipmentRlt::set_has_rs() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCEquipEquipmentRlt::clear_has_rs() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCEquipEquipmentRlt::clear_rs() {
  rs_ = 0;
  clear_has_rs();
}
inline ::google::protobuf::int32 SRPCEquipEquipmentRlt::rs() const {
  return rs_;
}
inline void SRPCEquipEquipmentRlt::set_rs(::google::protobuf::int32 value) {
  set_has_rs();
  rs_ = value;
}

// -------------------------------------------------------------------

// SRPCUnEquipEquipmentArg

// required int32 pos = 1;
inline bool SRPCUnEquipEquipmentArg::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCUnEquipEquipmentArg::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCUnEquipEquipmentArg::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCUnEquipEquipmentArg::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline ::google::protobuf::int32 SRPCUnEquipEquipmentArg::pos() const {
  return pos_;
}
inline void SRPCUnEquipEquipmentArg::set_pos(::google::protobuf::int32 value) {
  set_has_pos();
  pos_ = value;
}

// -------------------------------------------------------------------

// SRPCUnEquipEquipmentRlt

// required int32 rs = 1;
inline bool SRPCUnEquipEquipmentRlt::has_rs() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCUnEquipEquipmentRlt::set_has_rs() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCUnEquipEquipmentRlt::clear_has_rs() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCUnEquipEquipmentRlt::clear_rs() {
  rs_ = 0;
  clear_has_rs();
}
inline ::google::protobuf::int32 SRPCUnEquipEquipmentRlt::rs() const {
  return rs_;
}
inline void SRPCUnEquipEquipmentRlt::set_rs(::google::protobuf::int32 value) {
  set_has_rs();
  rs_ = value;
}

// -------------------------------------------------------------------

// SRPCSellItemArg

// required int32 itempos = 1;
inline bool SRPCSellItemArg::has_itempos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCSellItemArg::set_has_itempos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCSellItemArg::clear_has_itempos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCSellItemArg::clear_itempos() {
  itempos_ = 0;
  clear_has_itempos();
}
inline ::google::protobuf::int32 SRPCSellItemArg::itempos() const {
  return itempos_;
}
inline void SRPCSellItemArg::set_itempos(::google::protobuf::int32 value) {
  set_has_itempos();
  itempos_ = value;
}

// -------------------------------------------------------------------

// SRPCSellItemRlt

// required int32 money = 1;
inline bool SRPCSellItemRlt::has_money() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCSellItemRlt::set_has_money() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCSellItemRlt::clear_has_money() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCSellItemRlt::clear_money() {
  money_ = 0;
  clear_has_money();
}
inline ::google::protobuf::int32 SRPCSellItemRlt::money() const {
  return money_;
}
inline void SRPCSellItemRlt::set_money(::google::protobuf::int32 value) {
  set_has_money();
  money_ = value;
}

// required int32 badge = 2;
inline bool SRPCSellItemRlt::has_badge() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SRPCSellItemRlt::set_has_badge() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SRPCSellItemRlt::clear_has_badge() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SRPCSellItemRlt::clear_badge() {
  badge_ = 0;
  clear_has_badge();
}
inline ::google::protobuf::int32 SRPCSellItemRlt::badge() const {
  return badge_;
}
inline void SRPCSellItemRlt::set_badge(::google::protobuf::int32 value) {
  set_has_badge();
  badge_ = value;
}

// -------------------------------------------------------------------

// SRPCUseItemArg

// required int32 pos = 1;
inline bool SRPCUseItemArg::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCUseItemArg::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCUseItemArg::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCUseItemArg::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline ::google::protobuf::int32 SRPCUseItemArg::pos() const {
  return pos_;
}
inline void SRPCUseItemArg::set_pos(::google::protobuf::int32 value) {
  set_has_pos();
  pos_ = value;
}

// -------------------------------------------------------------------

// SRPCUseItemRlt

// required int32 rs = 1;
inline bool SRPCUseItemRlt::has_rs() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCUseItemRlt::set_has_rs() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCUseItemRlt::clear_has_rs() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCUseItemRlt::clear_rs() {
  rs_ = 0;
  clear_has_rs();
}
inline ::google::protobuf::int32 SRPCUseItemRlt::rs() const {
  return rs_;
}
inline void SRPCUseItemRlt::set_rs(::google::protobuf::int32 value) {
  set_has_rs();
  rs_ = value;
}

// -------------------------------------------------------------------

// SRPCComposeItemArg

// required int32 type = 1;
inline bool SRPCComposeItemArg::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCComposeItemArg::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCComposeItemArg::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCComposeItemArg::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 SRPCComposeItemArg::type() const {
  return type_;
}
inline void SRPCComposeItemArg::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// repeated int32 indexs = 2;
inline int SRPCComposeItemArg::indexs_size() const {
  return indexs_.size();
}
inline void SRPCComposeItemArg::clear_indexs() {
  indexs_.Clear();
}
inline ::google::protobuf::int32 SRPCComposeItemArg::indexs(int index) const {
  return indexs_.Get(index);
}
inline void SRPCComposeItemArg::set_indexs(int index, ::google::protobuf::int32 value) {
  indexs_.Set(index, value);
}
inline void SRPCComposeItemArg::add_indexs(::google::protobuf::int32 value) {
  indexs_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SRPCComposeItemArg::indexs() const {
  return indexs_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SRPCComposeItemArg::mutable_indexs() {
  return &indexs_;
}

// -------------------------------------------------------------------

// SRPCComposeItemRlt

// required int32 rs = 1;
inline bool SRPCComposeItemRlt::has_rs() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRPCComposeItemRlt::set_has_rs() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRPCComposeItemRlt::clear_has_rs() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRPCComposeItemRlt::clear_rs() {
  rs_ = 0;
  clear_has_rs();
}
inline ::google::protobuf::int32 SRPCComposeItemRlt::rs() const {
  return rs_;
}
inline void SRPCComposeItemRlt::set_rs(::google::protobuf::int32 value) {
  set_has_rs();
  rs_ = value;
}

// -------------------------------------------------------------------

// SRPCSortItemsArg

// -------------------------------------------------------------------

// SRPCSortItemsRlt

// -------------------------------------------------------------------

// CRPCUpdateOneBagItem

// required int32 pos = 1;
inline bool CRPCUpdateOneBagItem::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CRPCUpdateOneBagItem::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CRPCUpdateOneBagItem::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CRPCUpdateOneBagItem::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline ::google::protobuf::int32 CRPCUpdateOneBagItem::pos() const {
  return pos_;
}
inline void CRPCUpdateOneBagItem::set_pos(::google::protobuf::int32 value) {
  set_has_pos();
  pos_ = value;
}

// -------------------------------------------------------------------

// CRPCUpdateOneEquipedItem

// required int32 pos = 1;
inline bool CRPCUpdateOneEquipedItem::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CRPCUpdateOneEquipedItem::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CRPCUpdateOneEquipedItem::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CRPCUpdateOneEquipedItem::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline ::google::protobuf::int32 CRPCUpdateOneEquipedItem::pos() const {
  return pos_;
}
inline void CRPCUpdateOneEquipedItem::set_pos(::google::protobuf::int32 value) {
  set_has_pos();
  pos_ = value;
}

// -------------------------------------------------------------------

// CRPCUpdateBagItems

// required int32 pos = 1;
inline bool CRPCUpdateBagItems::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CRPCUpdateBagItems::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CRPCUpdateBagItems::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CRPCUpdateBagItems::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline ::google::protobuf::int32 CRPCUpdateBagItems::pos() const {
  return pos_;
}
inline void CRPCUpdateBagItems::set_pos(::google::protobuf::int32 value) {
  set_has_pos();
  pos_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace RPCS

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fRpc_2eproto__INCLUDED
